export const filterCategories = {
  "Type de lieu": [
    "Restaurant",
    "Bar",
    "Café",
    "Parc",
    "Rooftop",
    "Musée",
    "Bar clandestin (speakeasy)",
    "Lieu éphémère",
    "Petite capacité (ambiance intime)",
    "Bar d'hôtel",
  ],
  Ambiance: [
    "Romantique",
    "Détendue",
    "Branchée",
    "Intime",
    "Animée",
    "Vue panoramique",
    "Musique live",
  ],
  "Options alimentaires": [
    "Menu végétarien",
    "Menu végan",
    "Options sans gluten",
    "Plats halal",
    "Cuisine italienne",
    "Cuisine japonaise",
    "Cuisine française",
    "Cuisine mexicaine",
    "Brunch",
    "Cuisine indienne",
    "Cuisine thaïlandaise",
    "Cuisine méditerranéenne",
    "Cuisine libanaise",
    "Cuisine africaine",
    "Cuisine coréenne",
    "Cuisine fusion",
    "Street food",
    "Menu gastronomique",
    "Snacks et tapas",
    "Bar à salade",
  ],
  "Spécificités des boissons": [
    "Cocktails artisanaux",
    "Large choix de vins",
    "Bières artisanales",
    "Thés et infusions spécialisés",
    "Café de spécialité",
    "Mocktails (sans alcool)",
  ],

  "Préférences musicales": [
    "Musique classique",
    "Jazz",
    "Rock",
    "Electro",
    "Hip-hop/Rap",
    "Pop",
    "Pas de musique",
  ],
  Services: [
    "Privatisation possible",
    "Lieu ouvert tard",
    "Serveurs multilingues",
    "Service en continu",
    "Espaces privés (alcôves, séparés...)",
    "Tables partagées",
    "Animaux acceptés",
  ],
  Budget: ["€ (économique)", "€€ (modéré)", "€€€ (cher)"],
  Activité: [
    "Jeux (Billard, Baby-foot, Fléchettes, Jeux de société...)",
    "Karaoké",
    "Spectacles en direct",
  ],
  Décoration: [
    "Moderne",
    "Vintage",
    "Cosy",
    "Luxueuse",
    "Insolite",
    "Thématique",
    "Instagrammable",
  ],
  "Niveau de bruit": ["Calme", "Modéré", "Bruyant"],
  "Type d’espace": ["Intérieur", "Extérieur", "Terrasse chauffée"],
  "Préférences saisonnières": ["Adapté à l’hiver", "Idéal pour l’été"],
  Popularité: [
    "4+ étoiles",
    "3+ étoiles",
    "Lieux tendance",
    "Nouveautés",
    "Recommandés",
  ],
};
